services:
     web:
       build: .
       volumes:
         - .:/back
       ports:
         - "8000:8000"
       env_file:
         - .env
       depends_on:
         - redis
     redis:
       image: redis:latest
       volumes:
         - .:/back/cache