services:
     web:
       build: .
       volumes:
         - .:/back
       ports:
         - "8000:8000"
       env_file:
         - .env
       depends_on:
         - redis
     redis:
       image: redis:latest
       volumes:
         - .:/back/cache
     test_db:
       image: postgres:latest
       env_file:
         - .env
       environment:
         - POSTGRES_PASSWORD=${DB_PASSWORD_TEST}
         - POSTGRES_USER=${DB_USER_TEST}
         - POSTGRES_DB=${DB_TEST_NAME_DB}
         - POSTGRES_HOST=${HOST_TEST}
