networks:
  dev:


services:
     web:
       build: .
       volumes:
         - .:/back
       ports:
         - "8000:8000"
       env_file:
         - .env
       depends_on:
         - redis
       networks:
         - dev
     redis:
       image: redis:latest
       volumes:
         - .:/back/cache
       networks:
         - dev
     nginx:
       image: nginx:latest
       volumes:
         - './nginx.conf:/etc/nginx/nginx.conf'
       depends_on:
         - redis
         - web
       ports:
         - "80:80"
         - "443:443"
       networks:
         - dev