networks:
  dev:


services:
     web:
       build: .
       volumes:
         - .:/back
       ports:
         - "8000:8000"
       env_file:
         - .env
       depends_on:
         - redis
       networks:
         - dev
     comp:
       image: killazius/compile-server:v1.0
       ports:
         - "1235:1235"
       env_file:
         - .env
       networks:
         - dev
     redis:
       image: redis:latest
       volumes:
         - .:/back/cache
       networks:
         - dev
     nginx:
       image: nginx:latest
       volumes:
         - '/etc/ssl/certs/certificate.crt:/etc/ssl/certs/certificate.crt'
         - '/etc/ssl/private/certificate.key:/etc/ssl/private/certificate.key'
         - './nginx.conf:/etc/nginx/nginx.conf'
       depends_on:
         - redis
         - web
       ports:
         - "80:80"
         - "443:443"
       networks:
         - dev
