# Generated by Django 5.1.1 on 2025-04-29 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamplesForTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python', models.TextField()),
                ('cpp', models.TextField()),
                ('go', models.TextField()),
            ],
            options={
                'db_table': 'ExamplesForTasks',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catTask', models.CharField(max_length=30, unique=True, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя задачки')),
                ('desc', models.TextField(max_length=1000)),
                ('hash_name', models.SlugField(editable=False)),
                ('first_test', models.TextField()),
                ('second_test', models.TextField()),
                ('third_test', models.TextField()),
                ('cost', models.IntegerField(default=0)),
                ('level', models.CharField(choices=[('H', 'Hard'), ('M', 'Medium'), ('E', 'Easy')], default='E', max_length=1)),
                ('patterns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listTasks.examplesfortask')),
                ('users_solved', models.ManyToManyField(db_table='SolvingTasksByUser', to=settings.AUTH_USER_MODEL)),
                ('cat', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='listTasks.type')),
            ],
            options={
                'db_table': 'Tasks',
            },
        ),
    ]
