# Generated by Django 5.1.1 on 2025-04-29 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('count_tasks_easy', models.IntegerField(default=0)),
                ('count_tasks_medium', models.IntegerField(default=0)),
                ('count_tasks_hard', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DatesInfoUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('day_start_row', models.DateField(null=True)),
                ('days_in_row', models.IntegerField(default=0)),
                ('max_days', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Date information',
                'verbose_name_plural': 'Dates information',
                'db_table': 'UsersSolutionStreak',
            },
        ),
    ]
